export const ACTION_TYPES = {
  INPUT_CHANGE: 'INPUT_CHANGE',
  PRINT_TEST_ACTION : 'PRINT_TEST_ACTION',
  SET_SEARCH_KEYWORD: 'SET_SEARCH_KEYWORD',
  GET_CATEGORIES: 'GET_CATEGORIES',
  SET_CATEGORIES: 'SET_CATEGORIES',
  GET_EVENTS: 'GET_EVENTS',
  SET_EVENTS: 'SET_EVENTS',
  GET_ADDRESS: 'GET_ADDRESS',
  SET_ADDRESS: 'SET_ADDRESS',
  SELECT_ADDRESS: 'SELECT_ADDRESS'
};
